
FROM ubuntu:trusty

# Set the working directory in the container
WORKDIR /app

RUN apt-get update; apt-get clean

# Add a user for running applications.
RUN useradd apps
RUN mkdir -p /home/apps && chown apps:apps /home/apps

# Install x11vnc.
RUN apt-get install -y x11vnc

# Install xvfb.
RUN apt-get install -y xvfb

# Install fluxbox.
RUN apt-get install -y fluxbox

# Install wget.
RUN apt-get install -y wget

# Install wmctrl.
RUN apt-get install -y wmctrl

# Set the Chrome repo.
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list

# Install Chrome.
RUN apt-get update && apt-get -y install google-chrome-stable

# Clone the repository and install dependencies
RUN git clone https://github.com/SYBIOTE/ee-bot .
RUN npm install


# Set the command to run when the container starts
CMD ["npm", "run", "dev"]
CMD 'scripts/bootstrap.sh'

# Set a healthcheck for the container
HEALTHCHECK --interval=10s --timeout=2s --retries=3 \
    CMD curl --fail http://localhost:4000/ || exit 1

# we check if the bot API is up and running or not
